# Generated by Django 3.2.9 on 2022-01-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20220107_1052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='user',
            new_name='user_id',
        ),
    ]
