# Generated by Django 3.2.9 on 2022-01-10 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_rename_user_contributors_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contributors',
            old_name='project',
            new_name='project_id',
        ),
    ]
