# Generated by Django 3.2.9 on 2022-01-12 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_alter_projects_author_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='author_user_id',
            new_name='author_user',
        ),
    ]
