# Generated by Django 3.2.9 on 2022-01-17 11:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0012_auto_20220112_1542'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributors',
            unique_together={('user', 'project')},
        ),
    ]
