# Generated by Django 3.2.9 on 2022-01-07 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contributors',
        ),
    ]
